project: default
source:
  repoURL: https://charts.crossplane.io/stable
  path: .
  targetRevision: 1.18.2
  helm:
    valueFiles:
      - >-
        https://raw.githubusercontent.com/PierreStephaneVoltaire/kubernetes-playground-crossplane/refs/heads/master/crossplane/values.yaml
  chart: crossplane
destination:
  server: https://kubernetes.default.svc
  namespace: crossplane-system
syncPolicy:
  automated:
    prune: true
    selfHeal: true
revisionHistoryLimit: 10
