apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: provider-aws
  namespace: argocd
spec:
  project: crossplane
  source:
    repoURL: https://github.com/PierreStephaneVoltaire/kubernetes-playground-crossplane
    targetRevision: master
    path: crossplane/aws
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
